#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# run the simulation and compute the forces
changeDictionary
decomposePar -force
mpirun -np 10 --oversubscribe renumberMesh -parallel
mpirun -np 10 --oversubscribe rhoPimpleFoam -parallel
