#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# run the simulation and compute the forces
decomposePar -force

mpirun -np 4 --oversubscribe rhoPimpleFoam -parallel
reconstructPar
rhoPimpleFoam -postProcess -func computeForces
